name: CI(release)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.8.0)'
        required: true
        default: 'v1.8.0'
        type: string

permissions:
  contents: write
  actions: write

env:
  RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.RELEASE_TAG }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Load Google Services File
        env:
          DATA: ${{ secrets.HA1_GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and sign APK with Gradle
        run: |
          ./gradlew assembleRelease
          echo "VERSION_CODE=$(find app/build/outputs/apk/release -name '*arm64-v8a.apk' | head -n 1 | grep -oP '(?<=release\+)\d+(?=_arm64-v8a)')" >> $GITHUB_ENV
        env:
          HA1_KEYSTORE_PASSWORD: ${{ secrets.HA1_KEYSTORE_PASSWORD }}
          HA1_GITHUB_TOKEN: ${{ secrets.HA1_GITHUB_TOKEN }}
          HA1_VERSION_SOURCE: 'release'

      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Han1meViewer ${{ env.RELEASE_TAG }}+${{ env.VERSION_CODE }}
          files: app/build/outputs/apk/release/Han1meViewer-v*.apk

  changelog:
    name: Generate Changelog
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: refs/tags/${{ env.RELEASE_TAG }}
          fetch-depth: 0
          fetch-tags: true

      - name: Generate Changelog
        id: generate_changelog
        uses: Night-stars-1/changelog-generator-action@main

      - name: Update Changelog
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          make_latest: true
