name: Full Compile Check

on:
  # Manually trigger workflow
  workflow_dispatch:

  # Also run automatically on any push
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Clean and compile the project
      - name: Build project (check syntax & compile errors)
        run: ./gradlew clean assembleDebug --stacktrace --info

      # Optional: Run lint to catch warnings
      - name: Run lint
        run: ./gradlew lint

      # Optional: Run unit tests
      - name: Run unit tests
        run: ./gradlew test
